<!DOCTYPE html>
<html lang=fr dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $title ?></title>
        <link rel="stylesheet" href="dist/css/master.css">
        <script src="dist/js/index.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="jumbotron">
                        <a href="">
                            <h2 class="display-6"><?= $title ?></h2>
                        </a>
                        <div id="result"></div>
                        <hr class="my-4">
                        <div id="content">
                            <form action="" method="post">
                                <div class="form-group mb-4">
                                    <label for="url"></label>
                                    <input class="form-control" type="text" size="70" name="url"
                                           id="url" required/>
                                </div>
                                <button class="btn btn-primary" type="submit" value="Download MP3" name="submit">Download MP3
                                </button>
                                <input type="hidden" name="token" id="token" value="<?php echo htmlspecialchars($token); ?>"/>
                            </form>
                        </div>
                        <hr class="my-4">
                        <div class="col-sm-12">
                            <ul class="list-group">
                                <?php foreach ($files as $file): ?>
                                    <li class="list-group-item"><a href="<?= 'output/' . basename($file) ?>"
                                                                   download> <?= basename($file) ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
